#!/usr/bin/env python

import os
import json
import asyncio
import logging
import time
from pathlib import Path
from typing import List, Dict, Any, Optional
import pandas as pd
from datetime import datetime

# Add project root directory to Python path
import sys

sys.path.append(str(Path(__file__).parent.parent))

from lightrag.llm.openai import openai_complete_if_cache
from dotenv import load_dotenv

load_dotenv(dotenv_path=".env", override=False)


class LLMAnswerEvaluator:
    def __init__(self, config):
        self.config = config
        self.evaluation_results = []
        self.existing_evaluations = {}
        self.setup_logging()
        self.load_existing_evaluations()

    def setup_logging(self):
        log_file = os.path.join(self.config.output_dir, "llm_evaluation.log")
        os.makedirs(self.config.output_dir, exist_ok=True)

        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s - %(levelname)s - %(message)s",
            handlers=[
                logging.FileHandler(log_file, encoding="utf-8"),
                logging.StreamHandler(sys.stdout),
            ],
        )
        self.logger = logging.getLogger("llm_evaluator")

    def get_accuracy_evaluation_prompt(
        self,
        question: str,
        expected_answer: str,
        generated_answer: str,
        evidence_pages: str = "",
        evidence_sources: str = "",
    ) -> str:
        prompt = f"""You are an expert evaluator tasked with assessing the accuracy of answers generated by a RAG (Retrieval-Augmented Generation) system.

**Task**: Evaluate whether the generated answer correctly responds to the given question based on the expected answer.

**Question**: {question}

**Expected Answer**: {expected_answer}

**Generated Answer**: {generated_answer}

**Evidence Pages**: {evidence_pages}

**Evidence Sources**: {evidence_sources}

**Evaluation Criteria**:
1. **Accuracy (0 or 1)**: Does the generated answer match the factual content of the expected answer?
   - 1: The generated answer is factually correct and aligns with the expected answer
   - 0: The generated answer is factually incorrect or contradicts the expected answer

**Instructions**:
- Focus on factual correctness, not writing style or format
- Consider partial matches: if the generated answer contains the correct information but includes additional context, it should still be considered accurate
- For numerical answers, check if the values match or are equivalent
- For list answers, check if all key elements are present
- If the expected answer is "Not answerable" and the generated answer indicates inability to answer, consider it accurate

**Output Format**:
Please respond with a JSON object containing only:
{{
    "accuracy": 0 or 1,
    "reasoning": "Brief explanation of your evaluation"
}}
"""
        return prompt

    def get_comprehensive_evaluation_prompt(
        self,
        question: str,
        expected_answer: str,
        generated_answer: str,
        evidence_pages: str = "",
        evidence_sources: str = "",
    ) -> str:
        prompt = f"""You are an expert evaluator assessing the quality of answers generated by a RAG system across multiple dimensions.

**Question**: {question}

**Expected Answer**: {expected_answer}

**Generated Answer**: {generated_answer}

**Evidence Pages**: {evidence_pages}

**Evidence Sources**: {evidence_sources}

**Evaluation Dimensions** (Rate each from 0 to 1):

1. **Accuracy (0 or 1)**: Factual correctness compared to expected answer
   - 1: Factually correct and aligns with expected answer
   - 0: Factually incorrect or contradicts expected answer

2. **Relevance (0 to 1)**: How well the answer addresses the question
   - 1.0: Directly and completely addresses the question
   - 0.5: Partially addresses the question
   - 0.0: Does not address the question

3. **Completeness (0 to 1)**: How comprehensive the answer is
   - 1.0: Provides complete information as expected
   - 0.5: Provides partial but useful information
   - 0.0: Incomplete or missing key information

4. **Faithfulness (0 to 1)**: Whether the answer is grounded in evidence
   - 1.0: Answer is fully supported by evidence
   - 0.5: Answer is partially supported by evidence
   - 0.0: Answer contains unsupported claims

5. **Clarity (0 to 1)**: How clear and understandable the answer is
   - 1.0: Very clear and well-structured
   - 0.5: Reasonably clear with minor issues
   - 0.0: Unclear or confusing

6. **Consistency (0 to 1)**: Internal consistency of the answer
   - 1.0: Completely consistent, no contradictions
   - 0.5: Mostly consistent with minor issues
   - 0.0: Contains contradictions or inconsistencies

**Special Cases**:
- If expected answer is "Not answerable" and generated answer appropriately indicates inability to answer, rate accuracy as 1
- Consider format requirements (e.g., if expected format is "List" but answer is string, note in reasoning)

**Output Format**:
Respond with a JSON object:
{{
    "accuracy": 0 or 1,
    "relevance": 0.0 to 1.0,
    "completeness": 0.0 to 1.0,
    "faithfulness": 0.0 to 1.0,
    "clarity": 0.0 to 1.0,
    "consistency": 0.0 to 1.0,
    "overall_score": 0.0 to 1.0,
    "reasoning": "Brief explanation of your evaluation for each dimension"
}}
"""
        return prompt

    def fix_json_format(self, json_content: str) -> str:
        import re

        try:
            json_content = re.sub(r"```json\s*\n?", "", json_content)
            json_content = re.sub(r"\n?```", "", json_content)
            json_content = json_content.strip()

            reasoning_pattern = r'"reasoning":\s*"'
            matches = list(re.finditer(reasoning_pattern, json_content))

            if len(matches) > 1:
                first_match_start = matches[0].start()

                quote_start = matches[0].end() - 1
                quote_count = 0
                end_pos = quote_start

                for i, char in enumerate(json_content[quote_start:], quote_start):
                    if char == '"' and (
                        i == quote_start or json_content[i - 1] != "\\"
                    ):
                        quote_count += 1
                        if quote_count == 2:
                            end_pos = i + 1
                            break

                before_first = json_content[:first_match_start]
                first_reasoning = json_content[first_match_start:end_pos]

                after_first = json_content[end_pos:]
                after_first = re.sub(
                    r',?\s*"reasoning":\s*"[^"]*(?:\\"[^"]*)*"', "", after_first
                )

                json_content = before_first + first_reasoning + after_first

            if json_content and not json_content.endswith("}"):
                open_braces = json_content.count("{")
                close_braces = json_content.count("}")
                if open_braces > close_braces:
                    if not json_content.rstrip().endswith(('"', "}", "]")):
                        if '"' in json_content and json_content.count('"') % 2 == 1:
                            json_content = json_content.rstrip() + '"'
                    json_content += "}" * (open_braces - close_braces)

            json_content = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", json_content)

            return json_content.strip()

        except Exception as e:
            self.logger.warning(f"Error while fixing JSON format: {e}")
            return json_content

    def create_fallback_evaluation(self, response: str) -> Dict[str, Any]:
        """Create a basic evaluation result when JSON parsing fails."""
        import re

        # Try to extract key information from the response.
        fallback_result = {
            "accuracy": None,
            "relevance": None,
            "completeness": None,
            "faithfulness": None,
            "clarity": None,
            "consistency": None,
            "overall_score": None,
            "reasoning": "JSON parsing failed, so detailed evaluation data is unavailable.",
        }

        # Try to extract the accuracy value.
        accuracy_patterns = [
            r'"accuracy":\s*(\d+)',
            r"accuracy.*?(\d+)",
            r"correct.*?(\d+)",
            r"accurate.*?(\d+)",
        ]

        for pattern in accuracy_patterns:
            match = re.search(pattern, response, re.IGNORECASE)
            if match:
                try:
                    accuracy_value = int(match.group(1))
                    if accuracy_value in [0, 1]:
                        fallback_result["accuracy"] = accuracy_value
                        break
                except ValueError:
                    continue

        # If no explicit accuracy value is found, infer it from keywords.
        if fallback_result["accuracy"] is None:
            positive_keywords = ["correct", "accurate", "right", "yes", "true", "match"]
            negative_keywords = [
                "incorrect",
                "wrong",
                "false",
                "no",
                "mismatch",
                "contradiction",
            ]

            response_lower = response.lower()
            if any(keyword in response_lower for keyword in positive_keywords):
                fallback_result["accuracy"] = 1
            elif any(keyword in response_lower for keyword in negative_keywords):
                fallback_result["accuracy"] = 0

        # Set a default value if it is still None.
        if fallback_result["accuracy"] is None:
            fallback_result["accuracy"] = 0  # Conservative fallback.

        # For comprehensive evaluation, try to extract additional metrics.
        if "relevance" in response.lower():
            relevance_match = re.search(
                r'"relevance":\s*([\d.]+)', response, re.IGNORECASE
            )
            if relevance_match:
                try:
                    fallback_result["relevance"] = float(relevance_match.group(1))
                except ValueError:
                    pass

        self.logger.info(
            f"Created fallback evaluation result: accuracy={fallback_result['accuracy']}"
        )
        return fallback_result

    async def evaluate_single_answer(
        self,
        question: str,
        expected_answer: str,
        generated_answer: str,
        evidence_pages: str = "",
        evidence_sources: str = "",
        doc_id: str = "",
        evaluation_type: str = "comprehensive",
    ) -> Dict[str, Any]:
        """Evaluate a single answer."""
        start_time = time.time()

        try:
            if evaluation_type == "accuracy_only":
                prompt = self.get_accuracy_evaluation_prompt(
                    question,
                    expected_answer,
                    generated_answer,
                    evidence_pages,
                    evidence_sources,
                )
            else:
                prompt = self.get_comprehensive_evaluation_prompt(
                    question,
                    expected_answer,
                    generated_answer,
                    evidence_pages,
                    evidence_sources,
                )

            self.logger.info(f"Starting answer evaluation (type: {evaluation_type})")
            self.logger.info(f"Question: {question[:100]}...")

            # Call the LLM for evaluation and retry automatically on timeout.
            response = None
            for attempt in range(1, self.config.max_retries + 1):
                try:
                    response = await asyncio.wait_for(
                        openai_complete_if_cache(
                            model="gpt-4o-mini",
                            prompt=prompt,
                            system_prompt="You are an expert evaluator. Provide accurate and fair evaluations based on the given criteria.",
                            api_key=self.config.api_key,
                            base_url=self.config.base_url,
                            temperature=0.1,  # Keep temperature low for consistent evaluation.
                            max_tokens=1000,
                        ),
                        timeout=self.config.request_timeout,
                    )
                    break
                except asyncio.TimeoutError:
                    self.logger.warning(
                        f"Evaluation timed out on attempt {attempt}/{self.config.max_retries}: exceeded {self.config.request_timeout} seconds"
                    )
                    if attempt >= self.config.max_retries:
                        raise

            evaluation_time = time.time() - start_time

            # Parse the JSON response.
            try:
                evaluation_result = json.loads(response)
            except json.JSONDecodeError:
                import re

                # First, try to extract content wrapped in ```json```.
                json_code_block_match = re.search(
                    r"```json\s*\n(.*?)\n```", response, re.DOTALL
                )
                if json_code_block_match:
                    json_content = json_code_block_match.group(1).strip()
                    try:
                        evaluation_result = json.loads(json_content)
                    except json.JSONDecodeError as e:
                        self.logger.warning(
                            f"Failed to parse JSON inside code block: {e}"
                        )
                        # Try to repair common JSON formatting issues such as duplicate reasoning fields.
                        json_content = self.fix_json_format(json_content)
                        try:
                            evaluation_result = json.loads(json_content)
                        except json.JSONDecodeError:
                            # Final fallback: create a basic evaluation result.
                            self.logger.warning(
                                "JSON repair failed; using fallback evaluation result"
                            )
                            evaluation_result = self.create_fallback_evaluation(
                                response
                            )
                else:
                    # Try to extract any JSON object from the response.
                    json_match = re.search(r"\{.*\}", response, re.DOTALL)
                    if json_match:
                        json_content = json_match.group().strip()
                        try:
                            evaluation_result = json.loads(json_content)
                        except json.JSONDecodeError:
                            json_content = self.fix_json_format(json_content)
                            try:
                                evaluation_result = json.loads(json_content)
                            except json.JSONDecodeError:
                                # Final fallback: create a basic evaluation result.
                                self.logger.warning(
                                    "JSON repair failed; using fallback evaluation result"
                                )
                                evaluation_result = self.create_fallback_evaluation(
                                    response
                                )
                    else:
                        raise ValueError(
                            "Could not extract valid JSON from the response"
                        )

            # Add metadata.
            evaluation_result.update(
                {
                    "doc_id": doc_id,
                    "question": question,
                    "expected_answer": expected_answer,
                    "generated_answer": generated_answer,
                    "evidence_pages": evidence_pages,
                    "evidence_sources": evidence_sources,
                    "evaluation_type": evaluation_type,
                    "evaluation_time": evaluation_time,
                    "timestamp": datetime.now().isoformat(),
                    "success": True,
                    "error": None,
                }
            )

            self.logger.info(f"Evaluation completed in {evaluation_time:.2f} seconds")
            return evaluation_result

        except asyncio.TimeoutError:
            evaluation_time = time.time() - start_time
            error_msg = (
                f"Evaluation timed out after {self.config.request_timeout} seconds"
            )
            self.logger.error(error_msg)

            return {
                "doc_id": doc_id,
                "question": question,
                "expected_answer": expected_answer,
                "generated_answer": generated_answer,
                "evidence_pages": evidence_pages,
                "evidence_sources": evidence_sources,
                "evaluation_type": evaluation_type,
                "evaluation_time": evaluation_time,
                "timestamp": datetime.now().isoformat(),
                "success": False,
                "error": error_msg,
                "accuracy": None,
                "reasoning": None,
            }
        except Exception as e:
            evaluation_time = time.time() - start_time
            error_msg = f"Error during evaluation: {str(e)}"
            self.logger.error(error_msg)

            return {
                "doc_id": doc_id,
                "question": question,
                "expected_answer": expected_answer,
                "generated_answer": generated_answer,
                "evidence_pages": evidence_pages,
                "evidence_sources": evidence_sources,
                "evaluation_type": evaluation_type,
                "evaluation_time": evaluation_time,
                "timestamp": datetime.now().isoformat(),
                "success": False,
                "error": error_msg,
                "accuracy": None,
                "reasoning": None,
            }

    async def evaluate_rag_results(
        self,
        results_file: str,
        evaluation_type: str = "comprehensive",
        max_evaluations: int = None,
    ) -> None:
        """Evaluate a RAG results file."""
        self.logger.info(f"Starting evaluation for RAG results file: {results_file}")

        # Load RAG evaluation results.
        with open(results_file, "r", encoding="utf-8") as f:
            rag_results = json.load(f)

        if max_evaluations:
            rag_results = rag_results[:max_evaluations]
            self.logger.info(f"Limiting evaluations to: {max_evaluations}")

        total_items = len(rag_results)
        self.logger.info(f"Starting evaluation for {total_items} results")

        # Detect the result type.
        if rag_results and "vlm_result" in rag_results[0]:
            self.logger.info("Detected VLM result format")
            await self.evaluate_vlm_results(rag_results, evaluation_type)
        else:
            self.logger.info("Detected RAG result format")
            await self.evaluate_standard_rag_results(rag_results, evaluation_type)

    async def evaluate_multiple_results(
        self,
        results_files: List[str],
        evaluation_type: str = "comprehensive",
        max_evaluations: int = None,
    ) -> None:
        """Evaluate multiple result files, including RAG and VLM outputs."""
        self.logger.info(
            f"Starting evaluation for multiple result files: {results_files}"
        )

        start_time = time.time()
        all_results_by_type = {}

        # Load results grouped by file type.
        for results_file in results_files:
            self.logger.info(f"Loading results file: {results_file}")

            with open(results_file, "r", encoding="utf-8") as f:
                results = json.load(f)

            # Detect and tag the file type.
            if results and "vlm_result" in results[0]:
                file_type = "vlm"
                self.logger.info(f"Detected VLM result format: {len(results)} results")
            else:
                file_type = "rag"
                self.logger.info(f"Detected RAG result format: {len(results)} results")

            # Add file-type metadata to each result.
            for result in results:
                result["_file_type"] = file_type
                result["_source_file"] = results_file

            all_results_by_type[file_type] = {
                "results": results,
                "source_file": results_file,
            }

        # If a limit is provided, cap by question count rather than raw result count.
        if max_evaluations:
            for file_type in all_results_by_type:
                original_count = len(all_results_by_type[file_type]["results"])
                all_results_by_type[file_type]["results"] = all_results_by_type[
                    file_type
                ]["results"][:max_evaluations]
                limited_count = len(all_results_by_type[file_type]["results"])
                self.logger.info(
                    f"Limited {file_type} results: {original_count} -> {limited_count}"
                )

        # Merge all results for evaluation.
        all_results = []
        for file_type, data in all_results_by_type.items():
            all_results.extend(data["results"])

        total_items = len(all_results)
        skipped_count = 0
        completed_count = 0
        new_evaluations = []

        # Count existing evaluations.
        if self.existing_evaluations:
            existing_count = len(self.existing_evaluations)
            self.logger.info(
                f"Found {existing_count} existing LLM evaluations; duplicate evaluations will be skipped"
            )

        self.logger.info(f"Starting evaluation for a total of {total_items} results")

        # Evaluate all results.
        for i, result in enumerate(all_results, 1):
            self.logger.info(
                f"\n[{i}/{total_items}] Evaluating {result['_file_type'].upper()} result"
            )

            # Skip the entry if any error is present.
            if self.has_any_error(result):
                skipped_count += 1
                self.logger.info(
                    f"  Skipping query with errors: {self.get_error_summary(result)}"
                )
                continue

            if result["_file_type"] == "vlm":
                # Evaluate the VLM result.
                if result.get("vlm_result") and result["vlm_result"].get("success"):
                    method = "vlm"

                    # Check whether this evaluation already exists.
                    if self.is_evaluation_completed(
                        result["doc_id"], result["question"], method
                    ):
                        completed_count += 1
                        self.logger.info(f"  Skipping completed {method} evaluation")
                        # Add the existing result to the current batch.
                        existing_eval = self.get_existing_evaluation(
                            result["doc_id"], result["question"], method
                        )
                        if existing_eval:
                            existing_eval["source_file"] = result[
                                "_source_file"
                            ]  # Refresh source file metadata.
                            new_evaluations.append(existing_eval)
                        continue

                    eval_result = await self.evaluate_single_answer(
                        question=result["question"],
                        expected_answer=str(result["expected_answer"]),
                        generated_answer=str(result["vlm_result"]["result"]),
                        evidence_pages=result.get("evidence_pages", ""),
                        evidence_sources=result.get("evidence_sources", ""),
                        doc_id=result["doc_id"],
                        evaluation_type=evaluation_type,
                    )
                    eval_result["method"] = method
                    eval_result["model"] = result["vlm_result"].get("model", "unknown")
                    eval_result["source_file"] = result["_source_file"]

                    new_evaluations.append(eval_result)

                    # Update the lookup index.
                    key = (result["doc_id"], result["question"], method)
                    self.existing_evaluations[key] = eval_result

            else:  # RAG results
                # Evaluate the hybrid result.
                if result.get("hybrid_result") and result["hybrid_result"].get(
                    "success"
                ):
                    method = "hybrid"

                    # Check whether this evaluation already exists.
                    if self.is_evaluation_completed(
                        result["doc_id"], result["question"], method
                    ):
                        completed_count += 1
                        self.logger.info(f"  Skipping completed {method} evaluation")
                        # Add the existing result to the current batch.
                        existing_eval = self.get_existing_evaluation(
                            result["doc_id"], result["question"], method
                        )
                        if existing_eval:
                            existing_eval["source_file"] = result["_source_file"]
                            new_evaluations.append(existing_eval)
                    else:
                        hybrid_eval = await self.evaluate_single_answer(
                            question=result["question"],
                            expected_answer=str(result["expected_answer"]),
                            generated_answer=str(result["hybrid_result"]["result"]),
                            evidence_pages=result.get("evidence_pages", ""),
                            evidence_sources=result.get("evidence_sources", ""),
                            doc_id=result["doc_id"],
                            evaluation_type=evaluation_type,
                        )
                        hybrid_eval["method"] = method
                        hybrid_eval["source_file"] = result["_source_file"]

                        new_evaluations.append(hybrid_eval)

                        # Update the lookup index.
                        key = (result["doc_id"], result["question"], method)
                        self.existing_evaluations[key] = hybrid_eval

                # Evaluate the mix result.
                if result.get("mix_result") and result["mix_result"].get("success"):
                    method = "mix"

                    # Check whether this evaluation already exists.
                    if self.is_evaluation_completed(
                        result["doc_id"], result["question"], method
                    ):
                        completed_count += 1
                        self.logger.info(f"  Skipping completed {method} evaluation")
                        # Add the existing result to the current batch.
                        existing_eval = self.get_existing_evaluation(
                            result["doc_id"], result["question"], method
                        )
                        if existing_eval:
                            existing_eval["source_file"] = result["_source_file"]
                            new_evaluations.append(existing_eval)
                    else:
                        mix_eval = await self.evaluate_single_answer(
                            question=result["question"],
                            expected_answer=str(result["expected_answer"]),
                            generated_answer=str(result["mix_result"]["result"]),
                            evidence_pages=result.get("evidence_pages", ""),
                            evidence_sources=result.get("evidence_sources", ""),
                            doc_id=result["doc_id"],
                            evaluation_type=evaluation_type,
                        )
                        mix_eval["method"] = method
                        mix_eval["source_file"] = result["_source_file"]

                        new_evaluations.append(mix_eval)

                        # Update the lookup index.
                        key = (result["doc_id"], result["question"], method)
                        self.existing_evaluations[key] = mix_eval

                # Evaluate the naive result.
                if result.get("naive_result") and result["naive_result"].get("success"):
                    method = "naive"

                    # Check whether this evaluation already exists.
                    if self.is_evaluation_completed(
                        result["doc_id"], result["question"], method
                    ):
                        completed_count += 1
                        self.logger.info(f"  Skipping completed {method} evaluation")
                        # Add the existing result to the current batch.
                        existing_eval = self.get_existing_evaluation(
                            result["doc_id"], result["question"], method
                        )
                        if existing_eval:
                            existing_eval["source_file"] = result["_source_file"]
                            new_evaluations.append(existing_eval)
                    else:
                        naive_eval = await self.evaluate_single_answer(
                            question=result["question"],
                            expected_answer=str(result["expected_answer"]),
                            generated_answer=str(result["naive_result"]["result"]),
                            evidence_pages=result.get("evidence_pages", ""),
                            evidence_sources=result.get("evidence_sources", ""),
                            doc_id=result["doc_id"],
                            evaluation_type=evaluation_type,
                        )
                        naive_eval["method"] = method
                        naive_eval["source_file"] = result["_source_file"]

                        new_evaluations.append(naive_eval)

                        # Update the lookup index.
                        key = (result["doc_id"], result["question"], method)
                        self.existing_evaluations[key] = naive_eval

            # Save progress every 10 results.
            if i % 10 == 0:
                # Update evaluation_results and persist them.
                self.update_evaluation_results_list(new_evaluations)
                self.save_evaluation_results()
                self.logger.info(
                    f"Saved the first {len(self.evaluation_results)} evaluation results"
                )
                new_evaluations = []  # Clear the temporary list.

        total_time = time.time() - start_time

        # Update and save the final results.
        if new_evaluations:
            self.update_evaluation_results_list(new_evaluations)
        self.save_evaluation_results()

        # Log summary statistics.
        new_eval_count = (
            len(self.evaluation_results)
            - len(self.existing_evaluations)
            + len(new_evaluations)
        )
        if skipped_count > 0:
            self.logger.info(f"Skipped {skipped_count} queries with errors")
        if completed_count > 0:
            self.logger.info(f"Skipped {completed_count} completed evaluations")
        self.logger.info(f"Completed {new_eval_count} new evaluations")

        # Generate the evaluation report.
        self.generate_evaluation_report(total_time)

    async def evaluate_vlm_results(self, vlm_results: List[Dict], evaluation_type: str):
        """Evaluate VLM results."""
        start_time = time.time()
        skipped_count = 0
        completed_count = 0
        new_evaluations = []

        # Count existing evaluations.
        if self.existing_evaluations:
            existing_count = len(self.existing_evaluations)
            self.logger.info(
                f"Found {existing_count} existing LLM evaluations; duplicate evaluations will be skipped"
            )

        for i, vlm_result in enumerate(vlm_results, 1):
            self.logger.info(f"\n[{i}/{len(vlm_results)}] Evaluating VLM result")

            # Skip the entry if any error is present.
            if self.has_any_error(vlm_result):
                skipped_count += 1
                self.logger.info(
                    f"  Skipping VLM query with errors: {self.get_error_summary(vlm_result)}"
                )
                continue

            # Evaluate the VLM result.
            if vlm_result.get("vlm_result") and vlm_result["vlm_result"].get("success"):
                method = "vlm"

                # Check whether this evaluation already exists.
                if self.is_evaluation_completed(
                    vlm_result["doc_id"], vlm_result["question"], method
                ):
                    completed_count += 1
                    self.logger.info(f"  Skipping completed {method} evaluation")
                    # Add the existing result to the current batch.
                    existing_eval = self.get_existing_evaluation(
                        vlm_result["doc_id"], vlm_result["question"], method
                    )
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                    continue

                vlm_eval = await self.evaluate_single_answer(
                    question=vlm_result["question"],
                    expected_answer=str(vlm_result["expected_answer"]),
                    generated_answer=str(vlm_result["vlm_result"]["result"]),
                    evidence_pages=vlm_result.get("evidence_pages", ""),
                    evidence_sources=vlm_result.get("evidence_sources", ""),
                    doc_id=vlm_result["doc_id"],
                    evaluation_type=evaluation_type,
                )
                vlm_eval["method"] = method
                vlm_eval["model"] = vlm_result["vlm_result"].get("model", "unknown")

                new_evaluations.append(vlm_eval)

                # Update the lookup index.
                key = (vlm_result["doc_id"], vlm_result["question"], method)
                self.existing_evaluations[key] = vlm_eval

            # Save progress every 10 results.
            if i % 10 == 0:
                # Update evaluation_results and persist them.
                self.update_evaluation_results_list(new_evaluations)
                self.save_evaluation_results()
                self.logger.info(
                    f"Saved the first {len(self.evaluation_results)} evaluation results"
                )
                new_evaluations = []  # Clear the temporary list.

        total_time = time.time() - start_time

        # Update and save the final results.
        if new_evaluations:
            self.update_evaluation_results_list(new_evaluations)
        self.save_evaluation_results()

        # Log summary statistics.
        new_eval_count = len(new_evaluations) if new_evaluations else 0
        if skipped_count > 0:
            self.logger.info(f"Skipped {skipped_count} VLM queries with errors")
        if completed_count > 0:
            self.logger.info(f"Skipped {completed_count} completed evaluations")
        self.logger.info(f"Completed {new_eval_count} new evaluations")

        # Generate the evaluation report.
        self.generate_evaluation_report(total_time)

    async def evaluate_standard_rag_results(
        self, rag_results: List[Dict], evaluation_type: str
    ):
        """Evaluate standard RAG results for hybrid, mix, and naive methods."""
        start_time = time.time()
        skipped_count = 0
        completed_count = 0
        new_evaluations = []

        # Count existing evaluations.
        if self.existing_evaluations:
            existing_count = len(self.existing_evaluations)
            self.logger.info(
                f"Found {existing_count} existing LLM evaluations; duplicate evaluations will be skipped"
            )

        for i, rag_result in enumerate(rag_results, 1):
            self.logger.info(f"\n[{i}/{len(rag_results)}] Evaluating RAG result")

            # Skip the entry if any error is present.
            if self.has_any_error(rag_result):
                skipped_count += 1
                self.logger.info(
                    f"  Skipping RAG query with errors: {self.get_error_summary(rag_result)}"
                )
                continue

            # Evaluate the hybrid result.
            if rag_result.get("hybrid_result") and rag_result["hybrid_result"].get(
                "success"
            ):
                method = "hybrid"

                # Check whether this evaluation already exists.
                if self.is_evaluation_completed(
                    rag_result["doc_id"], rag_result["question"], method
                ):
                    completed_count += 1
                    self.logger.info(f"  Skipping completed {method} evaluation")
                    # Add the existing result to the current batch.
                    existing_eval = self.get_existing_evaluation(
                        rag_result["doc_id"], rag_result["question"], method
                    )
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                else:
                    hybrid_eval = await self.evaluate_single_answer(
                        question=rag_result["question"],
                        expected_answer=str(rag_result["expected_answer"]),
                        generated_answer=str(rag_result["hybrid_result"]["result"]),
                        evidence_pages=rag_result.get("evidence_pages", ""),
                        evidence_sources=rag_result.get("evidence_sources", ""),
                        doc_id=rag_result["doc_id"],
                        evaluation_type=evaluation_type,
                    )
                    hybrid_eval["method"] = method

                    new_evaluations.append(hybrid_eval)

                    # Update the lookup index.
                    key = (rag_result["doc_id"], rag_result["question"], method)
                    self.existing_evaluations[key] = hybrid_eval

            # Evaluate the mix result.
            if rag_result.get("mix_result") and rag_result["mix_result"].get("success"):
                method = "mix"

                # Check whether this evaluation already exists.
                if self.is_evaluation_completed(
                    rag_result["doc_id"], rag_result["question"], method
                ):
                    completed_count += 1
                    self.logger.info(f"  Skipping completed {method} evaluation")
                    # Add the existing result to the current batch.
                    existing_eval = self.get_existing_evaluation(
                        rag_result["doc_id"], rag_result["question"], method
                    )
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                else:
                    mix_eval = await self.evaluate_single_answer(
                        question=rag_result["question"],
                        expected_answer=str(rag_result["expected_answer"]),
                        generated_answer=str(rag_result["mix_result"]["result"]),
                        evidence_pages=rag_result.get("evidence_pages", ""),
                        evidence_sources=rag_result.get("evidence_sources", ""),
                        doc_id=rag_result["doc_id"],
                        evaluation_type=evaluation_type,
                    )
                    mix_eval["method"] = method

                    new_evaluations.append(mix_eval)

                    # Update the lookup index.
                    key = (rag_result["doc_id"], rag_result["question"], method)
                    self.existing_evaluations[key] = mix_eval

            # Evaluate the naive result.
            if rag_result.get("naive_result") and rag_result["naive_result"].get(
                "success"
            ):
                method = "naive"

                # Check whether this evaluation already exists.
                if self.is_evaluation_completed(
                    rag_result["doc_id"], rag_result["question"], method
                ):
                    completed_count += 1
                    self.logger.info(f"  Skipping completed {method} evaluation")
                    # Add the existing result to the current batch.
                    existing_eval = self.get_existing_evaluation(
                        rag_result["doc_id"], rag_result["question"], method
                    )
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                else:
                    naive_eval = await self.evaluate_single_answer(
                        question=rag_result["question"],
                        expected_answer=str(rag_result["expected_answer"]),
                        generated_answer=str(rag_result["naive_result"]["result"]),
                        evidence_pages=rag_result.get("evidence_pages", ""),
                        evidence_sources=rag_result.get("evidence_sources", ""),
                        doc_id=rag_result["doc_id"],
                        evaluation_type=evaluation_type,
                    )
                    naive_eval["method"] = method

                    new_evaluations.append(naive_eval)

                    # Update the lookup index.
                    key = (rag_result["doc_id"], rag_result["question"], method)
                    self.existing_evaluations[key] = naive_eval

            # Save progress every 10 results.
            if i % 10 == 0:
                # Update evaluation_results and persist them.
                self.update_evaluation_results_list(new_evaluations)
                self.save_evaluation_results()
                self.logger.info(
                    f"Saved the first {len(self.evaluation_results)} evaluation results"
                )
                new_evaluations = []  # Clear the temporary list.

        total_time = time.time() - start_time

        # Update and save the final results.
        if new_evaluations:
            self.update_evaluation_results_list(new_evaluations)
        self.save_evaluation_results()

        # Log summary statistics.
        new_eval_count = len(new_evaluations) if new_evaluations else 0
        if skipped_count > 0:
            self.logger.info(f"Skipped {skipped_count} RAG queries with errors")
        if completed_count > 0:
            self.logger.info(f"Skipped {completed_count} completed evaluations")
        self.logger.info(f"Completed {new_eval_count} new evaluations")

        # Generate the evaluation report.
        self.generate_evaluation_report(total_time)

    def save_evaluation_results(self):
        """Save evaluation results."""
        # Save the detailed JSON output.
        results_file = os.path.join(
            self.config.output_dir, "llm_evaluation_results.json"
        )
        results_tmp_file = f"{results_file}.tmp"
        with open(results_tmp_file, "w", encoding="utf-8") as f:
            json.dump(self.evaluation_results, f, ensure_ascii=False, indent=2)
        os.replace(results_tmp_file, results_file)

        # Save the CSV summary.
        summary_data = []
        for result in self.evaluation_results:
            summary_data.append(
                {
                    "doc_id": result["doc_id"],
                    "method": result.get("method", ""),
                    "source_file": result.get("source_file", ""),
                    "question": result["question"][:100] + "..."
                    if len(result["question"]) > 100
                    else result["question"],
                    "expected_answer": str(result["expected_answer"])[:100] + "..."
                    if len(str(result["expected_answer"])) > 100
                    else str(result["expected_answer"]),
                    "generated_answer": str(result["generated_answer"])[:200] + "..."
                    if len(str(result["generated_answer"])) > 200
                    else str(result["generated_answer"]),
                    "accuracy": result.get("accuracy"),
                    "relevance": result.get("relevance"),
                    "completeness": result.get("completeness"),
                    "faithfulness": result.get("faithfulness"),
                    "clarity": result.get("clarity"),
                    "consistency": result.get("consistency"),
                    "overall_score": result.get("overall_score"),
                    "evaluation_time": result.get("evaluation_time"),
                    "success": result.get("success"),
                    "error": result.get("error", ""),
                }
            )

        summary_file = os.path.join(
            self.config.output_dir, "llm_evaluation_summary.csv"
        )
        df = pd.DataFrame(summary_data)
        summary_tmp_file = f"{summary_file}.tmp"
        df.to_csv(summary_tmp_file, index=False, encoding="utf-8")
        os.replace(summary_tmp_file, summary_file)

    def generate_evaluation_report(self, total_time: float):
        """Generate an evaluation report."""
        total_evaluations = len(self.evaluation_results)
        successful_evaluations = [
            r for r in self.evaluation_results if r.get("success")
        ]

        if not successful_evaluations:
            self.logger.warning(
                "No successful evaluation results were found, so the report cannot be generated"
            )
            return

        # Group statistics by method.
        method_stats = {}
        source_file_stats = {}

        for result in successful_evaluations:
            method = result.get("method", "unknown")
            source_file = result.get("source_file", "unknown")

            # Method-level statistics.
            if method not in method_stats:
                method_stats[method] = []
            method_stats[method].append(result)

            # Source-file-level statistics.
            if source_file not in source_file_stats:
                source_file_stats[source_file] = {}
            if method not in source_file_stats[source_file]:
                source_file_stats[source_file][method] = []
            source_file_stats[source_file][method].append(result)

        report = f"""
# LLM Answer Evaluation Report

## Overall Statistics
- Total evaluations: {total_evaluations}
- Successful evaluations: {len(successful_evaluations)}
- Failed evaluations: {total_evaluations - len(successful_evaluations)}
- Total elapsed time: {total_time:.2f} seconds
- Average time per evaluation: {total_time/total_evaluations:.2f} seconds

## Evaluation Configuration
- Evaluation model: gpt-4o-mini
- Evaluation temperature: 0.1
- Max tokens: 1000
"""

        # Source-file breakdown was intentionally removed to avoid exposing dataset-level statistics.

        # Generate statistics for each method.
        for method, results in method_stats.items():
            accuracy_scores = [
                r.get("accuracy") for r in results if r.get("accuracy") is not None
            ]

            report += f"""
## {method.upper()} Method Results

### Accuracy Statistics
- Evaluated samples: {len(results)}
- Correct answers: {sum(accuracy_scores)}
- Accuracy rate: {(sum(accuracy_scores) / len(accuracy_scores) * 100):.1f}%

"""

            # Include additional metrics when available.
            if any(r.get("relevance") is not None for r in results):
                relevance_scores = [
                    r.get("relevance")
                    for r in results
                    if r.get("relevance") is not None
                ]
                completeness_scores = [
                    r.get("completeness")
                    for r in results
                    if r.get("completeness") is not None
                ]
                faithfulness_scores = [
                    r.get("faithfulness")
                    for r in results
                    if r.get("faithfulness") is not None
                ]
                clarity_scores = [
                    r.get("clarity") for r in results if r.get("clarity") is not None
                ]
                consistency_scores = [
                    r.get("consistency")
                    for r in results
                    if r.get("consistency") is not None
                ]
                overall_scores = [
                    r.get("overall_score")
                    for r in results
                    if r.get("overall_score") is not None
                ]

                if relevance_scores:
                    report += f"""### Multi-Dimensional Metrics
- Average relevance: {(sum(relevance_scores) / len(relevance_scores)):.3f}
- Average completeness: {(sum(completeness_scores) / len(completeness_scores)):.3f}
- Average faithfulness: {(sum(faithfulness_scores) / len(faithfulness_scores)):.3f}
- Average clarity: {(sum(clarity_scores) / len(clarity_scores)):.3f}
- Average consistency: {(sum(consistency_scores) / len(consistency_scores)):.3f}
- Average overall score: {(sum(overall_scores) / len(overall_scores)):.3f}

"""

        # Compare methods.
        if len(method_stats) > 1:
            report += """
## Method Comparison

| Method | Samples | Accuracy | Average Overall Score |
|------|--------|--------|--------------|
"""
            for method, results in method_stats.items():
                accuracy_scores = [
                    r.get("accuracy") for r in results if r.get("accuracy") is not None
                ]
                overall_scores = [
                    r.get("overall_score")
                    for r in results
                    if r.get("overall_score") is not None
                ]

                accuracy_rate = (
                    (sum(accuracy_scores) / len(accuracy_scores) * 100)
                    if accuracy_scores
                    else 0
                )
                avg_overall = (
                    (sum(overall_scores) / len(overall_scores)) if overall_scores else 0
                )

                report += f"| {method} | {len(results)} | {accuracy_rate:.1f}% | {avg_overall:.3f} |\n"

        # Analyze all documents, not only those with multiple methods.
        doc_comparison = {}
        for result in successful_evaluations:
            original_doc_id = result["doc_id"]
            method = result.get("method", "unknown")
            source_file_path = result.get("source_file", "")
            folder_name = (
                os.path.basename(os.path.dirname(source_file_path))
                if source_file_path
                else ""
            )
            # Build a display doc ID prefixed with the folder identifier when available.
            display_doc_id = (
                f"{folder_name}/{original_doc_id}" if folder_name else original_doc_id
            )

            if display_doc_id not in doc_comparison:
                doc_comparison[display_doc_id] = {}
            if method not in doc_comparison[display_doc_id]:
                doc_comparison[display_doc_id][method] = []
            doc_comparison[display_doc_id][method].append(result)

        # Show document analysis regardless of how many methods were used.
        if doc_comparison:
            # Split documents into multi-method and single-method groups.
            multi_method_docs = {
                doc_id: methods
                for doc_id, methods in doc_comparison.items()
                if len(methods) > 1
            }
            single_method_docs = {
                doc_id: methods
                for doc_id, methods in doc_comparison.items()
                if len(methods) == 1
            }

            if multi_method_docs:
                report += f"""
## Same-Document Method Comparison

{len(multi_method_docs)} documents were evaluated by multiple methods:

| Document ID | Method | Correct Answers / Total Questions | Accuracy |
|--------|------|-------------------|--------|
"""
                for doc_id_display, methods in multi_method_docs.items():
                    for method, results in methods.items():
                        accuracy_scores = [
                            r.get("accuracy")
                            for r in results
                            if r.get("accuracy") is not None
                        ]
                        accuracy_count = sum(accuracy_scores)
                        total_count = len(accuracy_scores)
                        accuracy_rate = (
                            (accuracy_count / total_count * 100)
                            if total_count > 0
                            else 0
                        )

                        short_doc_id = (
                            doc_id_display[:30] + "..."
                            if len(doc_id_display) > 30
                            else doc_id_display
                        )
                        report += f"| {short_doc_id} | {method} | {accuracy_count}/{total_count} | {accuracy_rate:.1f}% |\n"

            if single_method_docs:
                # Choose the method to display, preferring VLM when available.
                available_methods = list(method_stats.keys())
                primary_method = (
                    "vlm" if "vlm" in available_methods else available_methods[0]
                )

                report += f"""
## Document-Level Results ({primary_method.upper()} Method)

Accuracy performance by document:

| Document ID | Correct Answers / Total Questions | Accuracy | Document Type |
|--------|-------------------|--------|----------|
"""
                # Build document rows for display.
                doc_performance = []
                for doc_id_display, methods in single_method_docs.items():
                    if primary_method in methods:
                        results = methods[primary_method]
                        accuracy_scores = [
                            r.get("accuracy")
                            for r in results
                            if r.get("accuracy") is not None
                        ]
                        accuracy_count = sum(accuracy_scores)
                        total_count = len(accuracy_scores)
                        accuracy_rate = (
                            (accuracy_count / total_count * 100)
                            if total_count > 0
                            else 0
                        )

                        # Infer document type information.
                        doc_types = set()
                        for r in results:
                            evidence_sources = r.get("evidence_sources", "")
                            if "arxiv" in evidence_sources.lower():
                                doc_types.add("Academic paper")
                            elif "10k" in doc_id_display.lower():
                                doc_types.add("Financial report")
                            elif any(
                                keyword in doc_id_display.lower()
                                for keyword in ["manual", "guide", "handbook"]
                            ):
                                doc_types.add("Manual / guide")
                            elif any(
                                keyword in doc_id_display.lower()
                                for keyword in ["report", "survey"]
                            ):
                                doc_types.add("Research report")
                            else:
                                doc_types.add("Other")

                        doc_type = ", ".join(doc_types) if doc_types else "Unknown"

                        doc_performance.append(
                            {
                                "doc_id": doc_id_display,
                                "accuracy_count": accuracy_count,
                                "total_count": total_count,
                                "accuracy_rate": accuracy_rate,
                                "doc_type": doc_type,
                            }
                        )

                # Sort by numeric folder prefix in the document ID when available.
                def _folder_num_from_doc_id(doc_id: str) -> int:
                    if "/" in doc_id:
                        folder = doc_id.split("/", 1)[0]
                        if folder.isdigit():
                            return int(folder)
                    # Put entries without a parseable numeric prefix at the end.
                    return 10**9

                doc_performance.sort(
                    key=lambda x: (_folder_num_from_doc_id(x["doc_id"]), x["doc_id"])
                )

                # Display all documents.
                display_docs = doc_performance
                for doc_info in display_docs:
                    short_doc_id = (
                        doc_info["doc_id"][:30] + "..."
                        if len(doc_info["doc_id"]) > 30
                        else doc_info["doc_id"]
                    )
                    report += f"| {short_doc_id} | {doc_info['accuracy_count']}/{doc_info['total_count']} | {doc_info['accuracy_rate']:.1f}% | {doc_info['doc_type']} |\n"

                # Aggregate statistics by document type.
                type_stats = {}
                for doc_info in doc_performance:
                    doc_type = doc_info["doc_type"]
                    if doc_type not in type_stats:
                        type_stats[doc_type] = {
                            "count": 0,
                            "total_questions": 0,
                            "correct_answers": 0,
                        }
                    type_stats[doc_type]["count"] += 1
                    type_stats[doc_type]["total_questions"] += doc_info["total_count"]
                    type_stats[doc_type]["correct_answers"] += doc_info[
                        "accuracy_count"
                    ]

                report += """
### Statistics by Document Type

| Document Type | Document Count | Total Questions | Correct Answers | Accuracy |
|----------|----------|----------|------------|--------|
"""
                for doc_type, stats in type_stats.items():
                    accuracy_rate = (
                        (stats["correct_answers"] / stats["total_questions"] * 100)
                        if stats["total_questions"] > 0
                        else 0
                    )
                    report += f"| {doc_type} | {stats['count']} | {stats['total_questions']} | {stats['correct_answers']} | {accuracy_rate:.1f}% |\n"

        report += f"""

## Output Files
- Detailed evaluation results: {os.path.join(self.config.output_dir, 'llm_evaluation_results.json')}
- Evaluation summary: {os.path.join(self.config.output_dir, 'llm_evaluation_summary.csv')}
- Evaluation log: {os.path.join(self.config.output_dir, 'llm_evaluation.log')}
"""

        # Save the report.
        report_file = os.path.join(self.config.output_dir, "llm_evaluation_report.md")
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(report)

        self.logger.info("\n" + "=" * 50)
        self.logger.info("LLM evaluation completed!")
        self.logger.info(
            f"Detailed results: {os.path.join(self.config.output_dir, 'llm_evaluation_results.json')}"
        )
        self.logger.info(
            f"Summary: {os.path.join(self.config.output_dir, 'llm_evaluation_summary.csv')}"
        )
        self.logger.info(f"Report: {report_file}")
        self.logger.info("=" * 50)

    def has_any_error(self, result: Dict[str, Any]) -> bool:
        """Check whether the result contains any error."""
        # Check the top-level error.
        if result.get("error"):
            return True

        # Check the VLM result error.
        vlm_result = result.get("vlm_result")
        if vlm_result and (
            vlm_result.get("error") or not vlm_result.get("success", True)
        ):
            return True

        # Check the RAG hybrid result error.
        hybrid_result = result.get("hybrid_result")
        if hybrid_result and (
            hybrid_result.get("error") or not hybrid_result.get("success", True)
        ):
            return True

        # Check the RAG mix result error.
        mix_result = result.get("mix_result")
        if mix_result and (
            mix_result.get("error") or not mix_result.get("success", True)
        ):
            return True

        # Check the RAG naive result error.
        naive_result = result.get("naive_result")
        if naive_result and (
            naive_result.get("error") or not naive_result.get("success", True)
        ):
            return True

        return False

    def get_error_summary(self, result: Dict[str, Any]) -> str:
        """Return a concise summary of evaluation errors."""
        errors = []

        # Top-level error.
        if result.get("error"):
            error_msg = result["error"]
            if "document not found" in error_msg.lower():
                errors.append("Document not found")
            else:
                errors.append(f"Top-level error: {error_msg[:50]}...")

        # VLM error.
        vlm_result = result.get("vlm_result")
        if vlm_result and (
            vlm_result.get("error") or not vlm_result.get("success", True)
        ):
            error_msg = vlm_result.get("error", "VLM query failed")
            if "context_length_exceeded" in error_msg:
                errors.append("VLM token limit exceeded")
            else:
                errors.append(f"VLM error: {error_msg[:50]}...")

        # RAG errors.
        hybrid_result = result.get("hybrid_result")
        if hybrid_result and (
            hybrid_result.get("error") or not hybrid_result.get("success", True)
        ):
            error_msg = hybrid_result.get("error", "Hybrid query failed")
            errors.append(f"Hybrid error: {error_msg[:50]}...")

        mix_result = result.get("mix_result")
        if mix_result and (
            mix_result.get("error") or not mix_result.get("success", True)
        ):
            error_msg = mix_result.get("error", "Mix query failed")
            errors.append(f"Mix error: {error_msg[:50]}...")

        naive_result = result.get("naive_result")
        if naive_result and (
            naive_result.get("error") or not naive_result.get("success", True)
        ):
            error_msg = naive_result.get("error", "Naive query failed")
            errors.append(f"Naive error: {error_msg[:50]}...")

        return "; ".join(errors) if errors else "Unknown error"

    def load_existing_evaluations(self):
        """Load previously saved evaluation results."""
        results_file = os.path.join(
            self.config.output_dir, "llm_evaluation_results.json"
        )

        if os.path.exists(results_file):
            try:
                with open(results_file, "r", encoding="utf-8") as f:
                    existing_data = json.load(f)

                self.evaluation_results = existing_data
                self.logger.info(
                    f"Loaded {len(existing_data)} existing LLM evaluation results"
                )

                # Build a fast lookup index: {(doc_id, question, method): result}
                for result in existing_data:
                    key = (
                        result["doc_id"],
                        result["question"],
                        result.get("method", ""),
                    )
                    self.existing_evaluations[key] = result

                self.logger.info(
                    f"Built a lookup index for {len(self.existing_evaluations)} LLM evaluation results"
                )

            except Exception as e:
                self.logger.warning(
                    f"Error loading existing LLM evaluation results: {e}; starting from scratch"
                )
                self.evaluation_results = []
                self.existing_evaluations = {}
        else:
            self.logger.info(
                "No existing LLM evaluation results file found; starting from scratch"
            )

    def is_evaluation_completed(self, doc_id: str, question: str, method: str) -> bool:
        """Check whether the specified evaluation has already been completed."""
        key = (doc_id, question, method)
        if key in self.existing_evaluations:
            result = self.existing_evaluations[key]
            # Check whether the evaluation completed successfully.
            if result.get("success") is True and result.get("accuracy") is not None:
                return True
        return False

    def get_existing_evaluation(self, doc_id: str, question: str, method: str):
        """Return an existing evaluation result if available."""
        key = (doc_id, question, method)
        return self.existing_evaluations.get(key)

    def update_evaluation_results_list(self, new_results: List[Dict[str, Any]]):
        """Update the evaluation results list by replacing matching old entries."""
        # Remove existing duplicate evaluations before appending new ones.
        existing_keys = set()
        for result in new_results:
            key = (result["doc_id"], result["question"], result.get("method", ""))
            existing_keys.add(key)

        # Remove old duplicate results.
        self.evaluation_results = [
            r
            for r in self.evaluation_results
            if (r["doc_id"], r["question"], r.get("method", "")) not in existing_keys
        ]

        # Append new results.
        self.evaluation_results.extend(new_results)

        self.logger.debug(
            f"Updated LLM evaluation results; current total count: {len(self.evaluation_results)}"
        )

    def persist_single_evaluation(self, evaluation_result: Dict[str, Any]):
        """Persist a single evaluation immediately for fine-grained resume support."""
        self.update_evaluation_results_list([evaluation_result])
        self.save_evaluation_results()

    async def evaluate_qa_files(
        self,
        qa_files: List[str],
        evaluation_type: str = "comprehensive",
        max_evaluations: Optional[int] = None,
    ) -> None:
        """Evaluate a group of QA result files containing question, answer, and correct_answer fields."""
        start_time = time.time()
        self.logger.info(f"Starting QA file evaluation for {len(qa_files)} files")

        skipped_count = 0
        completed_count = 0
        new_eval_count = 0

        # Count existing evaluations.
        if self.existing_evaluations:
            existing_count = len(self.existing_evaluations)
            self.logger.info(
                f"Found {existing_count} existing LLM evaluations; duplicate evaluations will be skipped"
            )

        total_items = 0

        for file_idx, qa_file in enumerate(qa_files, 1):
            self.logger.info(
                f"\n[{file_idx}/{len(qa_files)}] Processing QA file: {qa_file}"
            )
            try:
                with open(qa_file, "r", encoding="utf-8") as f:
                    qa_items = json.load(f)
            except Exception as e:
                self.logger.warning(f"Failed to load QA file: {qa_file}, error: {e}")
                continue

            if not isinstance(qa_items, list):
                self.logger.warning(
                    f"Invalid QA file format (expected an array), skipped: {qa_file}"
                )
                continue

            # Limit the number of evaluations per file if requested.
            if max_evaluations:
                qa_items = qa_items[:max_evaluations]

            total_items += len(qa_items)

            # Infer doc_id from a PDF in the same directory, or fall back to the directory name.
            qa_dir = os.path.dirname(qa_file)
            try:
                dir_entries = os.listdir(qa_dir)
            except Exception:
                dir_entries = []
            pdf_names = [name for name in dir_entries if name.lower().endswith(".pdf")]
            doc_id_base = pdf_names[0] if pdf_names else os.path.basename(qa_dir)

            for i, item in enumerate(qa_items, 1):
                question = str(item.get("question", "")).strip()
                expected_answer = str(item.get("correct_answer", "")).strip()
                generated_answer = str(item.get("answer", "")).strip()

                if not question:
                    skipped_count += 1
                    self.logger.info("  Skipping item with a missing question")
                    continue

                method = "qa"
                doc_id = doc_id_base

                # Check whether this evaluation already exists.
                if self.is_evaluation_completed(doc_id, question, method):
                    completed_count += 1
                    self.logger.info("  Skipping completed QA evaluation")
                    continue

                eval_result = await self.evaluate_single_answer(
                    question=question,
                    expected_answer=expected_answer,
                    generated_answer=generated_answer,
                    evidence_pages="",
                    evidence_sources="",
                    doc_id=doc_id,
                    evaluation_type=evaluation_type,
                )

                eval_result["method"] = method
                eval_result["source_file"] = qa_file

                # Update the index for deduplication.
                key = (doc_id, question, method)
                self.existing_evaluations[key] = eval_result
                self.persist_single_evaluation(eval_result)
                new_eval_count += 1
                self.logger.info(
                    f"  Saved current question evaluation result [{file_idx}/{len(qa_files)} file, {i}/{len(qa_items)} question]"
                )

        total_time = time.time() - start_time

        # Save once more so the report is generated from the latest results.
        self.save_evaluation_results()

        # Log summary statistics.
        if skipped_count > 0:
            self.logger.info(f"Skipped {skipped_count} invalid QA items")
        if completed_count > 0:
            self.logger.info(f"Skipped {completed_count} completed evaluations")
        self.logger.info(f"Completed {new_eval_count} new evaluations")

        # Generate the evaluation report.
        self.generate_evaluation_report(total_time)

    async def evaluate_qa_directory(
        self,
        qa_data_dir: str,
        evaluation_type: str = "comprehensive",
        max_evaluations: Optional[int] = None,
    ) -> None:
        """Scan and evaluate all `qa_results_naive_mm*.json` files in a directory."""
        self.logger.info(f"Starting QA directory scan: {qa_data_dir}")
        base_path = Path(qa_data_dir)
        if not base_path.exists():
            self.logger.error(f"QA directory does not exist: {qa_data_dir}")
            return

        qa_files: List[str] = []
        # Support `qa_results_naive_mm.json` as well.
        patterns = ["**/qa_results_naive_mm.json", "**/qa_results_naive_mm*.json"]
        for pattern in patterns:
            for p in base_path.glob(pattern):
                if p.is_file():
                    qa_files.append(str(p))

        # Deduplicate and sort for stable output.
        qa_files = sorted(list(set(qa_files)))

        if not qa_files:
            self.logger.warning(
                "No QA result files found matching qa_results_naive_mm*.json"
            )
            return

        self.logger.info(f"Discovered {len(qa_files)} QA result files")
        await self.evaluate_qa_files(qa_files, evaluation_type, max_evaluations)


class EvaluationConfig:
    def __init__(self, args):
        # Support multiple result files.
        if hasattr(args, "rag_results_files") and args.rag_results_files:
            self.rag_results_files = args.rag_results_files
            self.rag_results_file = None  # Backward compatibility.
        else:
            self.rag_results_file = args.rag_results_file
            self.rag_results_files = (
                [args.rag_results_file] if args.rag_results_file else []
            )

        self.output_dir = args.output_dir
        self.api_key = args.api_key
        self.base_url = args.base_url
        self.evaluation_type = args.evaluation_type
        self.max_evaluations = args.max_evaluations
        self.qa_data_dir = getattr(args, "qa_data_dir", None)
        self.request_timeout = 15
        self.max_retries = 3


def main():
    import argparse

    parser = argparse.ArgumentParser(description="LLM answer evaluator")

    # Support multiple result-file inputs (RAG/VLM), which can coexist with the QA directory option.
    group = parser.add_mutually_exclusive_group(required=False)
    group.add_argument(
        "--rag-results-file",
        "-r",
        help="Path to a single RAG evaluation results file (JSON)",
    )
    group.add_argument(
        "--rag-results-files",
        "-rf",
        nargs="+",
        help="Paths to multiple result files (supports mixed RAG and VLM JSON files)",
    )
    parser.add_argument(
        "--qa-data-dir",
        "-qd",
        default=str((Path(__file__).parent / "data").resolve()),
        help="Directory containing qa_result*.json files (scanned recursively; default: code/docbench/data)",
    )

    parser.add_argument(
        "--output-dir",
        "-o",
        default="./evaluation_results_naive_mm",
        help="Output directory for evaluation results (default: ./llm_evaluation_results)",
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("LLM_BINDING_API_KEY"),
        help="OpenAI API key (defaults to the LLM_BINDING_API_KEY environment variable)",
    )
    parser.add_argument(
        "--base-url",
        default=os.getenv("LLM_BINDING_HOST"),
        help="Base API URL (optional)",
    )
    parser.add_argument(
        "--evaluation-type",
        "-t",
        choices=["accuracy_only", "comprehensive"],
        default="comprehensive",
        help="Evaluation type: accuracy_only or comprehensive (default: comprehensive)",
    )
    parser.add_argument(
        "--max-evaluations",
        "-m",
        type=int,
        help="Maximum number of evaluations to run (useful for testing; evaluates all results if omitted)",
    )

    args = parser.parse_args()

    # Check the API key.
    if not args.api_key:
        print("Error: an OpenAI API key is required")
        print("Set the LLM_BINDING_API_KEY environment variable or provide --api-key")
        return

    # Check result files.
    files_to_check = []
    if args.rag_results_file:
        files_to_check = [args.rag_results_file]
    elif args.rag_results_files:
        files_to_check = args.rag_results_files

    for file_path in files_to_check:
        if not os.path.exists(file_path):
            print(f"Error: result file does not exist: {file_path}")
            return

    # Create the configuration.
    config = EvaluationConfig(args)

    # Create the evaluator.
    evaluator = LLMAnswerEvaluator(config)

    # Start evaluation.
    print("LLM Answer Evaluator")
    print("=" * 50)

    if config.rag_results_files:
        if len(config.rag_results_files) == 1:
            print(f"RAG/VLM results file: {config.rag_results_files[0]}")
        else:
            print(f"RAG/VLM results files: {config.rag_results_files}")
    else:
        print(f"QA directory: {config.qa_data_dir}")

    print(f"Output directory: {config.output_dir}")
    print(f"Evaluation type: {config.evaluation_type}")
    if config.max_evaluations:
        print(f"Maximum evaluations: {config.max_evaluations}")
    print("=" * 50)
    print("\nStarting evaluation...")

    # Run the evaluation.
    try:
        if config.rag_results_files:
            if len(config.rag_results_files) > 1:
                # Multi-file evaluation.
                asyncio.run(
                    evaluator.evaluate_multiple_results(
                        config.rag_results_files,
                        config.evaluation_type,
                        config.max_evaluations,
                    )
                )
            else:
                # Single-file evaluation for backward compatibility.
                asyncio.run(
                    evaluator.evaluate_rag_results(
                        config.rag_results_files[0],
                        config.evaluation_type,
                        config.max_evaluations,
                    )
                )
        else:
            # Evaluate QA files discovered by directory scan.
            asyncio.run(
                evaluator.evaluate_qa_directory(
                    config.qa_data_dir, config.evaluation_type, config.max_evaluations
                )
            )
    except KeyboardInterrupt:
        print("\nInterrupted by user, exiting")
    except Exception as e:
        print(f"\nAn error occurred during evaluation: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    main()
